#!/usr/bin/env ruby

require 'json'

failed_specs = `cat tmp/spec_summary.log | grep 'rspec .'`.split("\n")

files_to_run = failed_specs.map do |spec|
  spec[5..-1].split(':').first
end.uniq

if ARGV.include?('-n')
  puts files_to_run.count
elsif ARGV.include?('-o')
	files_to_run.each { |file| `mine #{file}` }
elsif ARGV.include?('-l')
	print "#{files_to_run.join("\n")}"
else
	puts "#{files_to_run.join(' ')}"
end
